//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<bool> genero { get; set; }
        public string correoElectronico { get; set; }
        public string celular { get; set; }
        public byte[] pdf { get; set; }
        public byte[] firma { get; set; }
        public string direccion { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
